# Generated by Django 4.2.3 on 2024-10-25 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_ticket_license_plate_remove_ticket_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='headquarters',
            field=models.ForeignKey(blank=True, help_text='Indica a sede principal deste estacionamento, se for uma filial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiais', to='management.parking'),
        ),
    ]
