# Generated by Django 4.2.3 on 2024-10-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(help_text='Insira apenas o ano.'),
        ),
    ]
