# Generated by Django 4.2.3 on 2024-10-25 20:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_remove_cliente_cpf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='data_nascimento',
            new_name='birth_date',
        ),
    ]
